# Generated by Django 5.0.14 on 2026-06-22 16:12

import django.core.validators
import django.db.models.deletion
import entregas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('entregas', '0001_initial'), ('entregas', '0002_alter_cliente_options_alter_encomenda_options_and_more'), ('entregas', '0003_alter_cliente_cpf_alter_cliente_genero_and_more'), ('entregas', '0004_alter_cliente_cpf_alter_cliente_rg'), ('entregas', '0005_alter_cliente_cpf_alter_encomenda_descricao'), ('entregas', '0006_encomenda_valor_base_encomenda_valor_calculado_and_more'), ('entregas', '0007_alter_encomenda_valor_cobrado'), ('entregas', '0008_ativar_unaccent'), ('entregas', '0009_adicionar_observacao_descartado'), ('entregas', '0010_bloquear_duplicidade'), ('entregas', '0011_encomenda_remetente'), ('entregas', '0012_alter_encomenda_remetente'), ('entregas', '0013_retirada'), ('entregas', '0014_corrige_datas_retiradas'), ('entregas', '0015_adiciona_observacao_cliente'), ('entregas', '0016_palavrachave')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, error_messages={'unique': 'Já existe um cliente cadastrado com este CPF.'}, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Este campo deve conter apenas números (sem pontos ou traços).'), entregas.models.validar_cpf_algoritmo])),
                ('rg', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Este campo deve conter apenas números (sem pontos ou traços).')])),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da Encomenda')),
                ('data_chegada', models.DateTimeField(verbose_name='Data de Chegada')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('valor_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final Cobrado')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Retirada'), ('ENTREGUE', 'Entregue ao Cliente')], default='PENDENTE', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.cliente')),
                ('valor_base', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Valor Base (Tabela)')),
                ('valor_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Calculado (Sistema)')),
            ],
            options={
                'ordering': ['cliente__nome'],
                'verbose_name': 'Encomenda',
                'verbose_name_plural': 'Encomendas',
            },
        ),
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS unaccent;',
        ),
        migrations.AddField(
            model_name='encomenda',
            name='descartado',
            field=models.BooleanField(default=False, verbose_name='Descartar Encomenda'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='observacao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observação'),
        ),
        migrations.AlterUniqueTogether(
            name='encomenda',
            unique_together={('cliente', 'descricao', 'data_chegada')},
        ),
        migrations.AddField(
            model_name='encomenda',
            name='remetente',
            field=models.CharField(max_length=255, verbose_name='Remetente'),
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Retirada')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total Cobrado')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20, verbose_name='Status da Retirada')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador (Caixa)')),
                ('retirado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas_feitas', to='entregas.cliente', verbose_name='Retirado por')),
            ],
            options={
                'verbose_name': 'Retirada',
                'verbose_name_plural': 'Histórico de Retiradas',
                'ordering': ['-data_retirada'],
            },
        ),
        migrations.AddField(
            model_name='encomenda',
            name='retirada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomendas', to='entregas.retirada', verbose_name='Retirada Vinculada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255, verbose_name='Cliente')),
                ('palavra', models.CharField(max_length=255, verbose_name='Palavra-Chave')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Palavra-Chave',
                'verbose_name_plural': 'Palavras-Chaves',
                'ordering': ['-id'],
            },
        ),
    ]