# Generated by Django 6.0.1 on 2026-01-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='encomenda',
            options={'ordering': ['cliente__nome'], 'verbose_name': 'Encomenda', 'verbose_name_plural': 'Encomendas'},
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da Encomenda'),
        ),
    ]
