# Generated by Django 6.0.1 on 2026-01-26 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0004_alter_cliente_cpf_alter_cliente_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, error_messages={'unique': 'Já existe um cliente cadastrado com este CPF.'}, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Este campo deve conter apenas números (sem pontos ou traços).')]),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição da Encomenda'),
        ),
    ]
