# Generated by Django 6.0.1 on 2026-01-31 12:49

import django.core.validators
import entregas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0005_alter_cliente_cpf_alter_encomenda_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Valor Base (Tabela)'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='valor_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Calculado (Sistema)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, error_messages={'unique': 'Já existe um cliente cadastrado com este CPF.'}, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Este campo deve conter apenas números (sem pontos ou traços).'), entregas.models.validar_cpf_algoritmo]),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='valor_cobrado',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Valor Final Cobrado'),
        ),
    ]
