# Generated by Django 6.0.1 on 2026-01-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0006_encomenda_valor_base_encomenda_valor_calculado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='valor_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final Cobrado'),
        ),
    ]
