# Generated by Gemini manually
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0009_adicionar_observacao_descartado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='encomenda',
            unique_together={('cliente', 'descricao', 'data_chegada')},
        ),
    ]