# Generated by Django 5.0.14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0010_bloquear_duplicidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='remetente',
            field=models.CharField(default='-', max_length=255, verbose_name='Remetente'),
        ),
    ]