# Generated by Django 5.0.14
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0011_encomenda_remetente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='remetente',
            field=models.CharField(max_length=255, verbose_name='Remetente'),
        ),
    ]