# Generated by Django 5.0 on 2024-05-18 10:00 (Manual)
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.admin.models import LogEntry, CHANGE
from django.contrib.contenttypes.models import ContentType

def migrar_historico_encomendas(apps, schema_editor):
    Encomenda = apps.get_model('entregas', 'Encomenda')
    Retirada = apps.get_model('entregas', 'Retirada')
    User = apps.get_model('auth', 'User')

    default_user = User.objects.filter(is_superuser=True).first()
    if not default_user:
        default_user = User.objects.first()
    
    encomendas_velhas = Encomenda.objects.filter(status='ENTREGUE', retirada__isnull=True)
    datas_exatas = encomendas_velhas.values_list('data_entrega', flat=True).distinct()
    
    for data_exata in datas_exatas:
        if not data_exata: continue
        
        pacotes_da_baixa = encomendas_velhas.filter(data_entrega=data_exata)
        if not pacotes_da_baixa.exists(): continue
        
        primeiro_pacote = pacotes_da_baixa.first()
        valor_somado = sum([p.valor_cobrado or 0 for p in pacotes_da_baixa])
        
        retirada = Retirada.objects.create(
            retirado_por=primeiro_pacote.cliente,
            operador=default_user,
            data_retirada=data_exata,
            valor_total=valor_somado,
            status='ATIVA'
        )
        
        pacotes_da_baixa.update(retirada=retirada)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entregas', '0012_alter_encomenda_remetente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Retirada')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total Cobrado')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20, verbose_name='Status da Retirada')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador (Caixa)')),
                ('retirado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas_feitas', to='entregas.cliente', verbose_name='Retirado por')),
            ],
            options={
                'verbose_name': 'Retirada',
                'verbose_name_plural': 'Histórico de Retiradas',
                'ordering': ['-data_retirada'],
            },
        ),
        migrations.AddField(
            model_name='encomenda',
            name='retirada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomendas', to='entregas.retirada', verbose_name='Retirada Vinculada'),
        ),
        
        migrations.RunPython(migrar_historico_encomendas),
    ]