# Generated by Django on 2024-05-28 14:50

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0014_corrige_datas_retiradas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
    ]