# Generated by Django on 2024-05-28 16:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0015_adiciona_observacao_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255, verbose_name='Cliente')),
                ('palavra', models.CharField(max_length=255, verbose_name='Palavra-Chave')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Palavra-Chave',
                'verbose_name_plural': 'Palavras-Chaves',
                'ordering': ['-id'],
            },
        ),
    ]