# Generated by Django

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0016_palavrachave'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1'),
        ),
    ]